url: https://coins-global.github.io/
baseurl: /coins-design-system

title: COINS Design System
author: Coins Construction Cloud
description: Coins Construction Cloud - Design System

cssLink: https://raw.githubusercontent.com/COINS-Naz/coins-design-system/main/css/app.css

sass:
  sass_dir: _sass
  style: compressed

github_username: COINS-GLOBAL
git_repo: coins-design-system